spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DEV_DATASOURCE_URL}
    username: ${DEV_DATASOURCE_USERNAME}
    password: ${DEV_DATASOURCE_PASSWORD}

security:
  jwt:
    token:
      secret-key: Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=
      expire-length: 36000000 # 60 minutes

api:
  randommer:
    api-key: 929e823be2f34ac09cfa5cf419b5e790
